// packages/react/src/dev/App.tsx
import { NeoButton } from '../components/NeoButton';

function App() {
  return (
    <div className="min-h-screen bg-neo-white p-8">
      <h1 className="text-4xl font-bold font-grotesk mb-8">Neobrut React Dev</h1>

      <section className="mb-8">
        <h2 className="text-2xl font-bold font-grotesk mb-4">Components</h2>
        <p className="text-neo-black mb-4">Add components here as you build them!</p>

        <NeoButton onClick={() => console.log('clicked!')}>Click me</NeoButton>
      </section>
    </div>
  );
}

export default App;

// packages/vue/src/dev/App.vue
<script setup lang="ts">
// Import components here as you build them
import NeoButton from '../components/NeoButton.vue';

console.log(NeoButton);
</script>

<template>
  <div class="min-h-screen bg-neo-white p-8">
    <h1 class="text-4xl font-bold font-grotesk mb-8">Neobrut Dev</h1>

    <section class="mb-8">
      <h2 class="text-2xl font-bold font-grotesk mb-4">Components</h2>
      <p class="text-neo-black">Add components here as you build them!</p>

      <!-- Example: -->
      <NeoButton>Click me</NeoButton>
    </section>
  </div>
</template>
